=== Rodez-IUT/dut-info2-filmprovider-YamkidoPMC/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED>
<!ATTLIST image title CDATA #IMPLIED>

<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT text (img*,em*,strong*) (#PCDATA)>
<!ELEMENT entete (text)>

<!ELEMENT titre >
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT auteur (prenom,nom)>
<!ELEMENT direction >
<!ELEMENT membres >
<!ELEMENT auteurs (auteur+|direction,membres)>
<!ELEMENT description >
<!ELEMENT prix >
<!ATTLIST livre numeroIsbn CDATA #REQUIRED>
<!ELEMENT livre (titre,auteurs+,description,prix)>

<!ELEMENT site (entete+,livre+)>

=== Rodez-IUT/dut-info2-filmprovider-YamkidoPMC/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE site SYSTEM "Librairie.dtd">
<site>
    <entete>
        <text>La super librairie
            <img src="jesaispas"></img>
            <strong> qui test la dtd</strong>
            <em> je suis barr√©</em> &copyright;
        </text>
    </entete>
    <livre numeroIsbn="E01">
        <titre>Les retards de yanis</titre>
            <auteur>
                <prenom>Pierre</prenom>
                <nom>Comb</nom>
            </auteur>
            <auteur>
                <prenom>test</prenom>
                <nom>ui</nom>
            </auteur>
        <description>
            Wtf les amis
        </description>
        <prix devise="dollar" tva="5.5" type="TTC">Chocapic</prix>
    </livre>

</site>
